#!/usr/bin/env python3
"""AIRAC cycle maths + artefact generation for the sector-file repos.

AIRAC cycles are exactly 28 days apart with no exceptions, so every cycle can be
COMPUTED from a single anchor. Nothing here reads airac-dates.csv — that file is
a generated human reference, regenerated by `--write`. It can never run out and
never needs hand-editing.

Verified against the 39 hand-maintained cycles that were in airac-dates.csv
(2601..2813): zero non-28-day gaps, every date a Thursday, YY always equal to the
effective date's year.

Usage:
  airac.py --write [--years-ahead N]   regenerate airac-dates.csv
  airac.py --tracker 2607              print the deployment tracker issue body
  airac.py --show [YYNN]               print one cycle (default: today's, if any)
  airac.py --selftest                  verify the formula against known cycles
"""

from __future__ import annotations

import argparse
import csv
import sys
from datetime import date, timedelta

# AIRAC 2601 was effective 2026-01-22. Everything derives from this.
ANCHOR_DATE = date(2026, 1, 22)
ANCHOR_YEAR_ORDINAL = 1  # it was the 1st cycle of 2026

CYCLE_DAYS = 28

MONTHS = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]

PROCESS_STEPS = [
    "Download and open the current sector file; check for plugin crashes",
    "Review pending pull requests",
    "Make GitHub release (tag + release notes)",
    "Pull GitHub main to GNG",
    "Ensure all files are checked",
    "Publish install package",
    "Create GNG release notes from the GitHub release notes",
    "Update the Discord message",
]

CATEGORY_HEADINGS = [
    ("Standard", "Standard Sectors"),
    ("Oceanic", "Oceanic"),
    ("FSS", "FSS"),
]


def generate(until: date):
    """Yield (cycle, date) from the anchor up to and including `until`.

    The cycle number resets to 01 whenever the effective date crosses into a new
    calendar year — which is how the published cycles are numbered.
    """
    d = ANCHOR_DATE
    ordinal = ANCHOR_YEAR_ORDINAL
    while d <= until:
        yield f"{d.year % 100:02d}{ordinal:02d}", d
        nxt = d + timedelta(days=CYCLE_DAYS)
        ordinal = 1 if nxt.year != d.year else ordinal + 1
        d = nxt


def cycle_for_date(d: date) -> str | None:
    """The cycle effective exactly on `d`, or None if `d` is not an AIRAC date."""
    if d < ANCHOR_DATE or (d - ANCHOR_DATE).days % CYCLE_DAYS != 0:
        return None
    for cycle, cd in generate(d):
        if cd == d:
            return cycle
    return None


def date_for_cycle(cycle: str) -> date | None:
    """The effective date of `cycle` (YYNN), or None if it isn't a real cycle."""
    if len(cycle) != 4 or not cycle.isdigit():
        return None
    # Search a generous horizon around the cycle's implied year.
    year = 2000 + int(cycle[:2])
    for c, d in generate(date(year + 1, 12, 31)):
        if c == cycle:
            return d
    return None


def human(d: date) -> str:
    return f"{d.day} {MONTHS[d.month - 1]} {d.year}"


def load_sectors(path: str = "repository-management/sectors.yml") -> list[dict]:
    """Minimal reader for sectors.yml.

    Deliberately dependency-free: the GitHub runners have no PyYAML preinstalled,
    and a `pip install` on every run is a needless failure mode for a file this
    simple.
    """
    sectors: list[dict] = []
    cur: dict | None = None
    with open(path, encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if s.startswith("#") or not s:
                continue
            if s.startswith("- repo:"):
                cur = {"repo": s.split(":", 1)[1].strip()}
                sectors.append(cur)
            elif cur is not None and ":" in s:
                k, v = s.split(":", 1)
                k = k.strip()
                if k in ("code", "name", "category"):
                    cur[k] = v.strip()
    return sectors


def write_csv(years_ahead: int, path: str = "repository-management/airac-dates.csv") -> int:
    until = date(date.today().year + years_ahead, 12, 31)
    rows = list(generate(until))
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["cycle", "date"])
        for cycle, d in rows:
            w.writerow([cycle, d.isoformat()])
    return len(rows)


def tracker_body(cycle: str, sectors_path: str = "repository-management/sectors.yml") -> str:
    d = date_for_cycle(cycle)
    if d is None:
        raise SystemExit(f"'{cycle}' is not a valid AIRAC cycle")

    sectors = load_sectors(sectors_path)
    out: list[str] = []
    out.append(f"# AIRAC {cycle} — Sector Deployment Tracker")
    out.append("")
    out.append(f"Effective {human(d)}. Tick a sector once all steps below are complete.")
    out.append("")
    out.append("## Process (per sector)")
    for i, step in enumerate(PROCESS_STEPS, 1):
        out.append(f"{i}. {step}")

    for cat, heading in CATEGORY_HEADINGS:
        rows = [s for s in sectors if s.get("category") == cat]
        if not rows:
            continue
        out.append("")
        out.append(f"## {heading}")
        for s in rows:
            code, repo, name = s["code"], s["repo"], s["name"]
            out.append(
                f"- [ ] **{name}** — "
                f"[Download](https://files.aero-nav.com/{code}) · "
                f"[GitHub](https://github.com/VATSIM-SSA/{repo}) · "
                f"[GNG](https://gng.aero-nav.com/{code}/)"
            )
    out.append("")
    return "\n".join(out)


# Cycles taken from the hand-maintained CSV this formula replaces. If the maths
# ever drifts from published reality, --selftest fails loudly.
KNOWN = {
    "2601": date(2026, 1, 22),
    "2606": date(2026, 6, 11),
    "2607": date(2026, 7, 9),
    "2613": date(2026, 12, 24),
    "2701": date(2027, 1, 21),
    "2813": date(2028, 12, 21),
}


def selftest() -> int:
    bad = 0
    for cycle, expected in KNOWN.items():
        got = date_for_cycle(cycle)
        ok = got == expected
        print(f"{'ok  ' if ok else 'FAIL'} {cycle} -> {got} (expected {expected})")
        bad += 0 if ok else 1
    for cycle, expected in KNOWN.items():
        got = cycle_for_date(expected)
        ok = got == cycle
        print(f"{'ok  ' if ok else 'FAIL'} {expected} -> {got} (expected {cycle})")
        bad += 0 if ok else 1
    # A non-AIRAC date must resolve to nothing.
    off = ANCHOR_DATE + timedelta(days=1)
    ok = cycle_for_date(off) is None
    print(f"{'ok  ' if ok else 'FAIL'} {off} -> None (non-AIRAC date)")
    bad += 0 if ok else 1
    print("\nFAILURES:" if bad else "\nAll checks passed.", bad or "")
    return 1 if bad else 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--write", action="store_true", help="regenerate airac-dates.csv")
    p.add_argument("--years-ahead", type=int, default=3, help="how far ahead to generate (default 3)")
    p.add_argument("--tracker", metavar="YYNN", help="print the tracker issue body for a cycle")
    p.add_argument("--show", nargs="?", const="", metavar="YYNN", help="print a cycle (default: today)")
    p.add_argument("--selftest", action="store_true", help="verify the formula against known cycles")
    a = p.parse_args()

    if a.selftest:
        return selftest()

    if a.write:
        n = write_csv(a.years_ahead)
        print(f"airac-dates.csv regenerated: {n} cycles through {date.today().year + a.years_ahead}")
        return 0

    if a.tracker:
        print(tracker_body(a.tracker))
        return 0

    if a.show is not None:
        if a.show:
            d = date_for_cycle(a.show)
            if d is None:
                raise SystemExit(f"'{a.show}' is not a valid AIRAC cycle")
            print(f"AIRAC {a.show}: {d.isoformat()} ({human(d)})")
        else:
            today = date.today()
            c = cycle_for_date(today)
            print(f"AIRAC {c}: {today} ({human(today)})" if c else f"{today} is not an AIRAC date")
        return 0

    p.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
